### ISSUE TITLE
Doesn't appear to work in 1.8.1.0

### ISSUE THREAD

**Issue by thepacmanfan** [deved-it/SalguaMagentoAddProduct#4]
I looked over the code for this extension, then installed it... It didn't seem to have the desired effect, and still takes users to an empty cart. I thought maybe it was due to the conflict with Simple Configurable Products (even though I'm only adding standalone simple products via querystring), so I set up a dev site and deleted the SCP extension code manually, since the extension is no longer recognized in my Magento Connect. No go.

I should also note we are using the OneStepCheckout extension, but I don't think it affects the cart page.

The add to cart URL I am testing is http://dev.concreteresurrection.com/urlcheckout/add?product=883

**Comment by thepacmanfan** [comment]
Turns out the product ID I was testing had a required option. It is working fine on products without required options.

**Comment by salgua** [comment]
Yes, I will do something for products with options

Inviato da iPhone

Il giorno 28/mar/2014, alle ore 20:16, thepacmanfan <
notifications@github.com> ha scritto:

Turns out the product ID I was testing had a required option. It is working
fine on products without required options.

## 

Reply to this email directly or view it on
GitHubhttps://github.com/salgua/SalguaMagentoAddProduct/issues/4#issuecomment-38957740
.

**Comment by gerbz** [comment]
Same issue here...
